### PR TITLE
add default empty string in `verbose` and `debug` functions to allow for `log.debug()` syntax.

### PR DESCRIPTION
**Pull request by DanielAsher**
this deals with #118 

I've not implemented the default for `warning`, `error` etc.

### CODE REVIEW

**Comment by dusek** [comment]
I am using it with `info` – would you mind adding that too?

**Comment by DanielAsher** [comment]
done :)

**Comment by dusek** [comment]
@DanielAsher thank you :smile:

**Comment by winkelsdorf** [comment]
+1 for merging

**Comment by DaveWoodCom** [comment]
Thanks for this PR. I've merged in another version, that adds even more flexibility. Check out the new `noMessageClosure` property. :)

**Pull request closed without merging**
