### PR TITLE
add podspec

### PR DESCRIPTION
**Pull request by orta**
Just got this in and working as the first working Swift pod [in Eidolon](https://github.com/artsy/eidolon/)
selfie-0

`swiftc` segfaults for me when running with a different optimization level though, shame.

### CODE REVIEW

**Comment by nicopuri** [comment]
+1

**Comment by nikita-leonov** [comment]
It would be great to have cocoapods integration. Should impact popularity of framework significantly.

**Comment by mwaterfall** [comment]
+1

**Comment by DaveWoodCom** [comment]
I've added this in. I don't use CocoaPods so I'm not entirely sure it's 100% correct, but it appears to work.Thanks for the PR.

https://cocoapods.org/pods/XCGLogger

**Pull request closed without merging**
