### PR TITLE
Update deployment targets to support Xcode 14.3+

### PR DESCRIPTION
**Pull request by einar-notland**
Xcode 14.3 requires deployment targets to be minimum iOS 11, tvOS 11 and WatchOS 4.

### CODE REVIEW

**Review by fcar12 — APPROVED** [review]

**Comment by einar-notland** [comment]
@DaveWoodCom I understand that you may not maintain this repo, but this is quite a minor change, any chance of getting it merged?

**Review by hanishassim — APPROVED** [review]

**Comment by mcdurdin** [comment]
This is a blocker for us as well; see keymanapp/keyman#8737. We'd prefer not to have to maintain our own fork if possible...

**Comment by adamsousa** [comment]
Any updates on getting this merged?

**Comment by DaveWoodCom** [comment]
XCGLogger 7.1.3 changes the deployment targets to the minimum allowed by Xcode 15.3.

**Pull request closed without merging**
