### PR TITLE
Swift3 alex

### PR DESCRIPTION
**Pull request by amolgupta**
Swift 3 support. Fix added for Xcode Beta 4

### CODE REVIEW

**Comment by MittaKarthik** [comment]
@DaveWoodCom Can you please merge this commit. So that we can compile project with Xcode 8 as well.

**Comment by amolgupta** [comment]
@MittaKarthik The developer seems to be inactive lately. Till the time they accept the pull request, you can use my branch as 
`  pod 'XCGLogger' , :git => 'https://github.com/amolgupta/XCGLogger.git', :branch => 'swift3_alex'
`

**Comment by MittaKarthik** [comment]
@amolgupta Thank you

**Comment by rnine** [comment]
You should make sure this works in the latest Xcode 8 beta (beta 6 at the time of this writing)

**Comment by DaveWoodCom** [comment]
Please see #143

@amolgupta Thanks for your branch. I wanted to use the fact that Swift 3 breaks pretty much every project as a way of cleaning up some of the technical debt that has accumulated in this project for a while. A lot of things in Swift have changed since this was originally released and now was a great time to clean up.

**Pull request closed without merging**
