### PR TITLE
Added Swift Package Manager support.

### PR DESCRIPTION
**Pull request by wadetregaskis**
This entailed things like:
• Moving the Objective-C code (XCGLogger.h) into a separate module so that the Swift Package Manager can handle it correctly (Swift Package Manager doesn't allow mixing of languages within any single module).  This also entailed renaming the _try() and throw() functions in the Objective-C version, to avoid conflict with the Swift ones.
• Moved the tests to the top-level "Tests" folder per Swift Package Manager expectations (Swift Package Manager will refuse to build anything in the package while there are tests in the 'Sources' folder).
• Moving the existing Xcode project up a level in the folder hierarchy, so that it’s in the right place for `xcode package generate-xcodeproj` to update it.
• Updating the various demo projects to account for the move.
• Renaming a few things (like XGCLogger.h to ObjcExceptionBridging.h) to satisfy Xcode’s assumptions about file names (Swift Package Manager blessedly doesn’t care).
• Adding missing import statements for dependent modules (i.e. Dispatch & Foundation).
• Adding instructions on using XCGLogger via Swift Package Manager.
• Removing the duplicate XCGLogger.h.
• Adding the Swift '.build' folder to .gitignore.
• Happening to update the target & scheme naming from “OS X” to “macOS”.

### CODE REVIEW

**Comment by wadetregaskis** [comment]
Unlike my prior pull request (#173), this version is AFAIK complete.  I updated all the demo projects, the README.md, everything.

**Comment by wadetregaskis** [comment]
One additional note - in order for anyone to be able to make use of this, you'll need to adjust your tag naming convention, to drop the "Version_" prefix and just have "X.Y.Z".  Swift Package Manager requires compliance with [Semantic Versioning](http://semver.org).

**Comment by a1049145827** [comment]
hello, when I use XCGLogger with 'swift package generate-xcodeproj' command, it failure with message like below:
No version tag found in (/Users/bruce/Desktop/PerfectTemplate-master/Packages/XCGLogger.git) package. Add a version tag with "git tag" command. Example: "git tag 0.1.0"
do you have any advice for me?

**Comment by DaveWoodCom** [comment]
Thanks for this PR. I really hate that this forces us to use a separate framework for a single .h file. Hopefully Apple will fix Objective-C exception handling soon. This should be in the next release (end of today most likely).

**Pull request merged**
