### PR TITLE
migrated to swift 2

### PR DESCRIPTION
**Pull request by Eldrinarion**
Hi, 
I upgraded the swift syntax to be swift2 compatible for the new Xcode 7.0 Beta.

I changed as well the podspec since I am not sure if it will still work on iOS7.
Additionally I've enabled code coverage for the project.

### CODE REVIEW

**Comment by beltex** [comment]
Hi @Eldrinarion!

Swift 2.0 can still target iOS 7 & OS X 10.9 as before.

**Comment by Eldrinarion** [comment]
Hi, thank you for the info, I will undo the change for the minimum required version.

**Comment by beltex** [comment]
np!

**Comment by DaveWoodCom** [comment]
Hi, thanks for this. I just got back from WWDC and am evaluating the overall architecture of XCGLogger to see if we can make even more improvements with the new stuff in Swift 2.

I can't merge this to master, as that has to remain Swift 1.2 compatible until Swift 2.0 is released. I'll create a branch for Swift 2.0 for use in the meantime. With a version bump of XCGLogger to 3.0.

**Comment by DaveWoodCom** [comment]
Thanks for the PR. I've pushed a swift_2.0 branch now that has these changes (a few handled slightly differently to avoid some bugs, see the do/try section handling the log file, and the handling of the thread name).

You may want to adjust your Xcode settings, in Preferences, under Text Editing, check the two options for trimming white space. There are a lot of lines in this PR that are just extra whitespace on a line. That makes it hard to merge in cleanly.

**Comment by Eldrinarion** [comment]
Ok thx I will have a look and adapt the whitespace settings.

**Pull request closed without merging**
