### PR TITLE
Fixed XCode 9 beta 6 compilation issue

### PR DESCRIPTION
**Pull request by rubenhak**
Adapting to changes in Swift 4 in regards to some deprecated String operations.

### CODE REVIEW

**Comment by GerritPost** [comment]
+1 

Please merge!

**Comment by Gerst20051** [comment]
https://github.com/DaveWoodCom/XCGLogger/pull/228

**Comment by petrmanek** [comment]
Ehm, so when is this going to be merged and released to production?

**Comment by DaveWoodCom** [comment]
Today is that day!

I've released my new app "All the Rings" [https://alltherings.fit/](https://alltherings.fit/?s=G) and will be pushing up the next version of XCGLogger today.

BTW, it would be really helpful if you'd download the app (it's free) and give it a spin. Bonus points if you tweet about it!

Thanks.

**Comment by Gerst20051** [comment]
WOW Dave! Nice Job!!! All The Rings looks awesome!!! 👍  💯  🥇  💥  🎊  🔥

**Comment by DaveWoodCom** [comment]
Merged into 6.0.0. Thanks for the PR.

**Pull request closed without merging**
